services:
  postgres:
    container_name: radavpo_db
    image: postgis/postgis:16-master
    env_file:
      - .env
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

  # api:
  #   container_name: radavpo_api
  #   build:
  #     context: ./
  #   env_file:
  #     - .env
  #   environment:
  #     - IS_DOCKER=true
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   expose:
  #     - ${PORT}:4040
  #   ports:
  #     - ${PORT}:4040
  #   command: sh -c "npm run db:setup && npm run start"
  #   depends_on:
  #     - postgres
  #   restart: always

volumes:
  pgdata:
